# Generated by Django 4.1.1 on 2022-09-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_no_of_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_of_items',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=10),
        ),
    ]
