# Generated by Django 4.1.1 on 2022-09-27 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0001_initial'),
        ('products', '0003_product_no_of_items_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_categorys', to='categorys.category'),
        ),
    ]
